version: '3.8'
services:
  fraud-api:
    build:
      context: ./src
      dockerfile: Analiz.API/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./Models:/app/Models
      - ./Data:/app/Data
      - ./Python:/app/Python
    networks:
      - fraud-network

networks:
  fraud-network:
    driver: bridge